# Generated by Django 3.2.1 on 2021-05-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('age', models.IntegerField(blank=True, max_length=2)),
                ('birthday', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
