# Generated by Django 3.2.1 on 2021-05-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yani_blog', '0002_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
