# Generated by Django 3.1.4 on 2021-05-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yani_blog', '0004_auto_20210507_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Title',
            new_name='title',
        ),
    ]
